name: Test GET
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test getting data
        id: query
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/todos?id=1'
          
      - name: Write the response payload to a JSON file
        run: |
          echo '${{ steps.query.outputs.response }}' > response.json
        shell: bash

      - name: Echo the contents of the JSON file
        run: cat response.json
        shell: bash