name: Test GET
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test getting data
        id: query
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/todos?id=1'
      - name: Print the response status
        run: echo ${{ steps.query.outputs.status }}
        shell: bash
      - name: Print the response headers
        run: echo ${{ steps.query.outputs.headers }}
        shell: bash
      - name: Print the response payload
        run: echo ${{ steps.query.outputs.response }}
        shell: bash