name: Test GET
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test getting data
        id: query
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: 'https://jsonplaceholder.typicode.com/todos?id=1'
      - name: Create file for response
        run: touch data.json
        shell: bash
      - name: Write response to file
        run: echo ${{ steps.query.outputs.response }} >> data.json
        shell: bash
      - name: Log file contents
        run: cat data.json
        shell: bash